# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Usage
  items:
    - label: 'Getting Started'
      link: '/usage/getting-started'
    - label: 'Device Operation'
      link: '/usage/operation'
    - label: 'Security'
      link: '/usage/security'
- label: Development
  items:
    - label: 'Getting Started'
      link: '/development/getting-started'
    - label: 'Code Features'
      link: '/development/code-features'
    - label: 'Code Structure'
      link: '/development/code-structure'
    - label: 'Adding Sensors'
      link: '/development/adding-sensors'
    - label: 'Configuring XBee Zigbee'
      link: '/development/config-xbee-zigbee'
    - label: 'Hardware Setup'
      link: '/development/hardware-setup'
    - label: 'Building Documentation'
      link: '/development/building-documentation'
- label: Communication
  items:
    - label: 'Bluetooth'
      link: '/communication/bluetooth'
    - label: 'HTTP REST'
      link: '/communication/http-rest'
    - label: 'XBee'
      link: '/communication/xbee'
- label: Support
